"""
Course Number: ENGR 13300
Semester: e.g. Fall 2024

Description:
    Calculates the amount of power that a turbine produces and converts to heat

Assignment Information:
    Assignment:     6.2.3 Py2 Team 3 Main
    Team ID:        022 - 11 
    Author:         Ankur Raghavan, raghav21@purdue.edu
    Author:         , @purdue.edu
    Author:         , @purdue.edu
    Author:         , @purdue.edu
    Date:           9/10/2024

Contributors:
    Name, login@purdue [repeat for each]

    My contributor(s) helped me:
    [ ] understand the assignment expectations without
        telling me how they will approach it.
    [ ] understand different ways to think about a solution
        without helping me plan my solution.
    [ ] think through the meaning of a specific error or
        bug present in my code without looking at my code.
    Note that if you helped somebody else with their code, you
    have to list that person as a contributor here as well.

Academic Integrity Statement:
    I have not used source code obtained from any unauthorized
    source, either modified or unmodified; nor have I provided
    another student access to my code.  The project I am
    submitting is my own original work.
"""

from py2_team_3_turbine_power_11 import turbine_power
from py2_team_3_heater_11 import heater

def main():
    l = 50
    p = 1.23
    C = 0.4
    # take input for wind velocity
    velocity_wind = float(input("Enter the velocity in m/s: "))
    # take input for time
    time = float(input("Enter the time in hours: "))*3600
    # calculate the energy output
    energy = turbine_power(p,l,velocity_wind, C)
    # calculate the heat output
    heat = heater(energy,time)
    #print results
    print(f"The power generated by the turbine is {energy:.1f} W")
    print(f"The amount of heat output by the heater is {heat:.1f} J")
    


if __name__ == "__main__":
    main()
